/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateMMG = /* GraphQL */ `
  subscription OnCreateMMG($filter: ModelSubscriptionMMGFilterInput) {
    onCreateMMG(filter: $filter) {
      id
      messageProfileIdentifier
      motherslocalrecordid
      mothernationalreportingjurisdiction
      mothersstateofresidence
      motherscountyofresidence
      motherszipcodeofresidence
      mothersbirthdate
      numberofpregnancies
      numberoftotallivebirths
      lastmenstrualperiod
      dateoffirstprenatalvisit
      prenatalvisitindicator
      trimesteroffirstprenatalvisit
      mothersethnicity
      mothersrace
      mothersmaritalstatus
      mothershivstatusduringpregnancy
      mothersclinicalstageofsyphilis
      motherssurveillancestageofsyphilis
      datewhenmotherreceivedfirstdoseofpencillin
      trimesteroffirstpenicillin
      motherstreatment
      appropriateserologicresponse
      nontreponemaltestatfirstvisit
      nontreponemaltestat28weeks
      nontreponemaltestatdelivery
      clinicalsignsofcongenitalsyphilis
      clinicalsignsindicator
      subjectoflabtestperformed
      testtype
      testresult
      nontreponemalserologictestresult
      dateoflabresult
      testresultquant
      resultunits
      specimencollectiondate
      vitalstatus
      birthweight
      gestationalage
      longbonexrays
      darkfieldexam
      csfwbccount
      csfproteinlevel
      csfvdrltestfinding
      infanttreated
      stillbirthindicator
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateMMG = /* GraphQL */ `
  subscription OnUpdateMMG($filter: ModelSubscriptionMMGFilterInput) {
    onUpdateMMG(filter: $filter) {
      id
      messageProfileIdentifier
      motherslocalrecordid
      mothernationalreportingjurisdiction
      mothersstateofresidence
      motherscountyofresidence
      motherszipcodeofresidence
      mothersbirthdate
      numberofpregnancies
      numberoftotallivebirths
      lastmenstrualperiod
      dateoffirstprenatalvisit
      prenatalvisitindicator
      trimesteroffirstprenatalvisit
      mothersethnicity
      mothersrace
      mothersmaritalstatus
      mothershivstatusduringpregnancy
      mothersclinicalstageofsyphilis
      motherssurveillancestageofsyphilis
      datewhenmotherreceivedfirstdoseofpencillin
      trimesteroffirstpenicillin
      motherstreatment
      appropriateserologicresponse
      nontreponemaltestatfirstvisit
      nontreponemaltestat28weeks
      nontreponemaltestatdelivery
      clinicalsignsofcongenitalsyphilis
      clinicalsignsindicator
      subjectoflabtestperformed
      testtype
      testresult
      nontreponemalserologictestresult
      dateoflabresult
      testresultquant
      resultunits
      specimencollectiondate
      vitalstatus
      birthweight
      gestationalage
      longbonexrays
      darkfieldexam
      csfwbccount
      csfproteinlevel
      csfvdrltestfinding
      infanttreated
      stillbirthindicator
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteMMG = /* GraphQL */ `
  subscription OnDeleteMMG($filter: ModelSubscriptionMMGFilterInput) {
    onDeleteMMG(filter: $filter) {
      id
      messageProfileIdentifier
      motherslocalrecordid
      mothernationalreportingjurisdiction
      mothersstateofresidence
      motherscountyofresidence
      motherszipcodeofresidence
      mothersbirthdate
      numberofpregnancies
      numberoftotallivebirths
      lastmenstrualperiod
      dateoffirstprenatalvisit
      prenatalvisitindicator
      trimesteroffirstprenatalvisit
      mothersethnicity
      mothersrace
      mothersmaritalstatus
      mothershivstatusduringpregnancy
      mothersclinicalstageofsyphilis
      motherssurveillancestageofsyphilis
      datewhenmotherreceivedfirstdoseofpencillin
      trimesteroffirstpenicillin
      motherstreatment
      appropriateserologicresponse
      nontreponemaltestatfirstvisit
      nontreponemaltestat28weeks
      nontreponemaltestatdelivery
      clinicalsignsofcongenitalsyphilis
      clinicalsignsindicator
      subjectoflabtestperformed
      testtype
      testresult
      nontreponemalserologictestresult
      dateoflabresult
      testresultquant
      resultunits
      specimencollectiondate
      vitalstatus
      birthweight
      gestationalage
      longbonexrays
      darkfieldexam
      csfwbccount
      csfproteinlevel
      csfvdrltestfinding
      infanttreated
      stillbirthindicator
      createdAt
      updatedAt
    }
  }
`;
